[unix_http_server]
file=%(here)s/.run/supervisor.sock
chmod=0600

[supervisord]
logfile=%(here)s/.run/supervisord.log
pidfile=%(here)s/.run/supervisord.pid
childlogdir=%(here)s/.run
logfile_maxbytes=5MB
logfile_backups=2

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(here)s/.run/supervisor.sock

[program:scnu-fastapi]
directory=%(here)s/../app
command=%(here)s/../.venv/bin/python %(here)s/../app/main.py
autostart=true
autorestart=true
startsecs=3
startretries=5
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=%(here)s/.run/app.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
environment=PYTHONUNBUFFERED="1"
